[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core==1.6",
]

[tool.poetry]
name = "tap-forem"
version = "0.0.1"
description = "`tap-forem` is a Singer tap for Forem, built with the Meltano SDK for Singer Taps."
authors = [
    "Edgar Ramírez-Mondragón <edgarrm358@gmail.com>",
]
keywords = [
    "ELT",
    "Forem",
    "singer.io",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "0.28.0"

[tool.poetry.group.dev.dependencies]
singer-sdk = {version="*", extras=["testing"]}

[tool.poetry.scripts]
# CLI declaration
"tap-forem" = 'tap_forem.tap:TapForem.cli'

[tool.ruff]
ignore = [
  "ANN101",  # missing-type-self
  "DJ",      # flake8-django
  "FIX002",  # line-contains-todo
]
line-length = 88
select = ["ALL"]
src = ["[[ tap_package_import_name ]]", "tests"]
target-version = "py37"
unfixable = [
  "ERA001",  # commented-out-code
]

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201",  # missing-return-type-public-function
  "S101",    # assert
  "SLF001",  # private-member-access
]

[tool.ruff.isort]
known-first-party = ["tap_forem"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = 3.9
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["backoff.*"]
ignore_missing_imports = true
